stages:
  - terraform-plan
  - terraform-apply

default:
  tags:
    - infra

.tf:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  before_script:
    - cd $TF_ROOT

tf-plan:main:
  extends:
    - .tf
  stage: terraform-plan
  resource_group: tf/main
  script:
    - gitlab-terraform plan | tee output
    - gitlab-terraform plan-json
    - |
      echo -e "\e[0Ksection_start:`date +%s`:glpa_summary\r\e[0KHeader of the summary"
      grep -E "Plan:|No changes" output | sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g"
      echo -e "\e[0Ksection_end:`date +%s`:glpa_summary\r\e[0K"
  artifacts:
    expire_in: 7 days
    paths:
      - $TF_ROOT/plan.cache
    reports:
      terraform: $TF_ROOT/plan.json
  variables:
    TF_STATE_NAME: main
    TF_ROOT: '.'

tf-apply:main:
  extends:
    - .tf
  stage: terraform-apply
  resource_group: tf/main
  needs:
    - tf-plan:main
  script:
    - gitlab-terraform apply | tee output
    - |
      echo -e "\e[0Ksection_start:`date +%s`:glpa_summary\r\e[0KHeader of the summary"
      grep "Apply complete!" output | sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g"
      echo -e "\e[0Ksection_end:`date +%s`:glpa_summary\r\e[0K"
  environment:
    name: main
    deployment_tier: production
  variables: !reference ["tf-plan:main", variables]
  rules:
    - if: $C0_GH_REF == "refs/heads/main"
      when: delayed
      start_in: 2 min
